version: '3.9'

services:
  vendure:
    container_name: dollup-vendure
    build: .
    ports:
      - "3000:3000"
    environment:
      - DB_TYPE=postgres
      - DB_HOST=185.158.132.8
      - DB_PORT=5543
      - DB_USERNAME=postgres
      - DB_PASSWORD=vendure123
      - DB_NAME=postgres
      - DB_SCHEMA=public
      - SSL_MODE=require
      - NODE_ENV=production
    restart: always
